### PR TITLE
Fix missing filename bug

### LINKED ISSUE #715: Filename is missing
Filename is missing for default datasets, uploaded local CSV data, and remote data loaded via URL.

image

### PR DESCRIPTION
**Pull request by felixcodes**
Fix #715 
Filenames work again :)

And thanks to @ssharif6 for digging around with me last night.

image

### CODE REVIEW

File: src/actions/dataset.ts [hunk 1]
```diff
@@ -60,17 +60,19 @@ export function datasetLoad(name: string, data: Data): DatasetLoad {
...
+      return buildSchemaAndDispatchDataReceive(data, config, dispatch, name);
     } else {
       throw new Error('dataset load error: dataset type not detected');
     }
   };
 };
 
-function buildSchemaAndDispatchDataReceive(data: InlineData, config: VoyagerConfig, dispatch: Dispatch<Action>) {
+function buildSchemaAndDispatchDataReceive(
+  data: InlineData, config: VoyagerConfig, dispatch: Dispatch<Action>, name: String
```
Comment (kanitw) [inline src/actions/dataset.ts]: Please use `string` rather than String :) 

https://stackoverflow.com/questions/14727044/typescript-difference-between-string-and-string
